/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventaris.atk.view;

import inventaris.atk.controllers.PemakaianController;
import java.awt.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author FiqieUlya
 */
public class Pemakaian extends javax.swing.JFrame {

    private final PemakaianController pemakaianController;
    /**
     * Creates new form Pemakaian
     */
    public Pemakaian() {
        initComponents();
        okButton1.setVisible(false);
        okButton2.setVisible(false);
        pemakaianController = new PemakaianController(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        penggunaan = new javax.swing.JPanel();
        booking = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        formBooking = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIdBooking = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jumlahBooking = new javax.swing.JSpinner();
        prosesBooking = new javax.swing.JButton();
        tanggalBooking = new com.toedter.calendar.JDateChooser();
        atkOrders1 = new javax.swing.JPanel();
        okButton1 = new javax.swing.JButton();
        viewBooking = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        pemakaian = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        formPemakaian = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jumlahPemakaian = new javax.swing.JSpinner();
        nipPemakain = new javax.swing.JTextField();
        prosesPemakaian = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        atkOrders2 = new javax.swing.JPanel();
        okButton2 = new javax.swing.JButton();
        viewPemakaian = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        bookingButton = new javax.swing.JButton();
        pemakaianButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 769));

        penggunaan.setBackground(new java.awt.Color(255, 255, 255));
        penggunaan.setLayout(new java.awt.CardLayout());

        jTabbedPane1.setToolTipText("");

        jLabel1.setText("NIM/NIP");

        jLabel2.setText("Tanggal Pesan");

        jLabel3.setText("Jumlah Jenis ATK");

        jumlahBooking.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        prosesBooking.setText("Proses");
        prosesBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesBookingActionPerformed(evt);
            }
        });

        tanggalBooking.setDateFormatString("YYYY-MM-DD");

        okButton1.setText("OK");
        okButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBookingLayout = new javax.swing.GroupLayout(formBooking);
        formBooking.setLayout(formBookingLayout);
        formBookingLayout.setHorizontalGroup(
            formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBookingLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formBookingLayout.createSequentialGroup()
                        .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50)
                        .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIdBooking)
                            .addComponent(jumlahBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                    .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(okButton1)
                        .addGroup(formBookingLayout.createSequentialGroup()
                            .addGap(290, 290, 290)
                            .addComponent(prosesBooking)))
                    .addComponent(atkOrders1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(638, Short.MAX_VALUE))
        );
        formBookingLayout.setVerticalGroup(
            formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBookingLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userIdBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(tanggalBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jumlahBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prosesBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atkOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Form", formBooking);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        hapus.setText("Hapus");

        javax.swing.GroupLayout viewBookingLayout = new javax.swing.GroupLayout(viewBooking);
        viewBooking.setLayout(viewBookingLayout);
        viewBookingLayout.setHorizontalGroup(
            viewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewBookingLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBookingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hapus)
                .addGap(402, 402, 402))
        );
        viewBookingLayout.setVerticalGroup(
            viewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBookingLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(hapus)
                .addGap(102, 102, 102))
        );

        jTabbedPane1.addTab("View", viewBooking);

        javax.swing.GroupLayout bookingLayout = new javax.swing.GroupLayout(booking);
        booking.setLayout(bookingLayout);
        bookingLayout.setHorizontalGroup(
            bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        bookingLayout.setVerticalGroup(
            bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        penggunaan.add(booking, "booking");

        jLabel4.setText("NIM/NIP");

        jLabel5.setText("Tanggal Pesan");

        jLabel6.setText("Jumlah Jenis ATK");

        prosesPemakaian.setText("Proses");
        prosesPemakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesPemakaianActionPerformed(evt);
            }
        });

        jDateChooser2.setDateFormatString("YYYY-MM-DD");

        javax.swing.GroupLayout atkOrders2Layout = new javax.swing.GroupLayout(atkOrders2);
        atkOrders2.setLayout(atkOrders2Layout);
        atkOrders2Layout.setHorizontalGroup(
            atkOrders2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        atkOrders2Layout.setVerticalGroup(
            atkOrders2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        okButton2.setText("OK");

        javax.swing.GroupLayout formPemakaianLayout = new javax.swing.GroupLayout(formPemakaian);
        formPemakaian.setLayout(formPemakaianLayout);
        formPemakaianLayout.setHorizontalGroup(
            formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPemakaianLayout.createSequentialGroup()
                .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okButton2)
                    .addComponent(atkOrders2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formPemakaianLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(42, 42, 42)
                            .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jumlahPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nipPemakain)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                        .addGroup(formPemakaianLayout.createSequentialGroup()
                            .addGap(292, 292, 292)
                            .addComponent(prosesPemakaian))))
                .addContainerGap(698, Short.MAX_VALUE))
        );
        formPemakaianLayout.setVerticalGroup(
            formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPemakaianLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nipPemakain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jumlahPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prosesPemakaian)
                .addGap(18, 18, 18)
                .addComponent(atkOrders2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton2)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("formPemakaian", formPemakaian);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Hapus");

        javax.swing.GroupLayout viewPemakaianLayout = new javax.swing.GroupLayout(viewPemakaian);
        viewPemakaian.setLayout(viewPemakaianLayout);
        viewPemakaianLayout.setHorizontalGroup(
            viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPemakaianLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        viewPemakaianLayout.setVerticalGroup(
            viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPemakaianLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton3)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("viewPemakaian", viewPemakaian);

        javax.swing.GroupLayout pemakaianLayout = new javax.swing.GroupLayout(pemakaian);
        pemakaian.setLayout(pemakaianLayout);
        pemakaianLayout.setHorizontalGroup(
            pemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemakaianLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pemakaianLayout.setVerticalGroup(
            pemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemakaianLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        penggunaan.add(pemakaian, "pemakaian");

        bookingButton.setText("Booking");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        pemakaianButton.setText("Pemakaian");
        pemakaianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemakaianButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bookingButton)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pemakaianButton)
                        .addGap(18, 18, 18)))
                .addComponent(penggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(bookingButton)
                .addGap(18, 18, 18)
                .addComponent(pemakaianButton)
                .addContainerGap(504, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 145, Short.MAX_VALUE)
                .addComponent(penggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed
        pemakaianController.openBooking();
    }//GEN-LAST:event_bookingButtonActionPerformed

    private void prosesBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesBookingActionPerformed
        atkOrders1.removeAll();
        
        int count= (Integer)jumlahBooking.getValue();
        Vector<String> atkName = pemakaianController.getATKName(); 
        createOrders(count, atkName,1);
        
        booking.revalidate();
        booking.repaint();
        okButton1.setVisible(true);
    }//GEN-LAST:event_prosesBookingActionPerformed

    private void prosesPemakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesPemakaianActionPerformed
        atkOrders2.removeAll();
        
        int count= (Integer)jumlahPemakaian.getValue();
        Vector<String> atkName = pemakaianController.getATKName(); 
        createOrders(count, atkName, 2);
        
        booking.revalidate();
        booking.repaint();
        okButton2.setVisible(true);
    }//GEN-LAST:event_prosesPemakaianActionPerformed

    private void okButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton1ActionPerformed
        String userId= userIdBooking.getText();
        String date= tanggalBooking.getDateFormatString();
   
    }//GEN-LAST:event_okButton1ActionPerformed

    private void pemakaianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemakaianButtonActionPerformed
       pemakaianController.openPemakaian();
    }//GEN-LAST:event_pemakaianButtonActionPerformed
    
    public void changeScreen(String screenName) {
        ((java.awt.CardLayout)penggunaan.getLayout()).show(penggunaan,screenName);
    }
    
    private void createOrders(int count, Vector<String> atkName, int state){
        atkOrders1.setLayout(new GridLayout(10,1));
        atkOrders2.setLayout(new GridLayout(10,1));
        
        for(int i=1; i<=count; i++){
            javax.swing.JPanel panel = new javax.swing.JPanel(new GridLayout(0,4));
            
            
            String itemname = "item" + i;
            String jumlahname = "jumlah" +i;
            javax.swing.JComboBox item = new javax.swing.JComboBox(atkName);
            javax.swing.JSpinner jumlah = new javax.swing.JSpinner();
            javax.swing.JLabel itemLabel = new javax.swing.JLabel("Item: ");
            javax.swing.JLabel jumlahLabel = new javax.swing.JLabel("Jumlah: ");
            
            panel.add(itemLabel, BorderLayout.EAST);
            panel.add(item);
            panel.add(jumlahLabel, BorderLayout.EAST);
            panel.add(jumlah);
            
            item.setName(itemname);
            jumlah.setName(jumlahname);
            itemLabel.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
            jumlahLabel.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
            if(state==1)
                atkOrders1.add(panel);
            else
                atkOrders2.add(panel);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemakaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atkOrders1;
    private javax.swing.JPanel atkOrders2;
    private javax.swing.JPanel booking;
    private javax.swing.JButton bookingButton;
    private javax.swing.JPanel formBooking;
    private javax.swing.JPanel formPemakaian;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JSpinner jumlahBooking;
    private javax.swing.JSpinner jumlahPemakaian;
    private javax.swing.JTextField nipPemakain;
    private javax.swing.JButton okButton1;
    private javax.swing.JButton okButton2;
    private javax.swing.JPanel pemakaian;
    private javax.swing.JButton pemakaianButton;
    private javax.swing.JPanel penggunaan;
    private javax.swing.JButton prosesBooking;
    private javax.swing.JButton prosesPemakaian;
    private com.toedter.calendar.JDateChooser tanggalBooking;
    private javax.swing.JTextField userIdBooking;
    private javax.swing.JPanel viewBooking;
    private javax.swing.JPanel viewPemakaian;
    // End of variables declaration//GEN-END:variables
}
