/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventaris.atk.view;

import inventaris.atk.controllers.PemakaianController;
import java.awt.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author FiqieUlya
 */
public class Pemakaian extends javax.swing.JFrame {

    private final PemakaianController pemakaianController;
    private String nPemakaian;
    private String nBooking;
    private String tPemakaian;
    private String tBooking;
    /**
     * Creates new form Pemakaian
     */
    public Pemakaian() {
        initComponents();
        okButton1.setVisible(false);
        okButton2.setVisible(false);
        pemakaianController = new PemakaianController(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        penggunaan = new javax.swing.JPanel();
        booking = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        formBooking = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIdBooking = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jumlahBooking = new javax.swing.JSpinner();
        prosesBooking = new javax.swing.JButton();
        tanggalBooking = new com.toedter.calendar.JDateChooser();
        atkOrders1 = new javax.swing.JPanel();
        okButton1 = new javax.swing.JButton();
        viewBooking = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBooking = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        detailBooking = new javax.swing.JTable();
        pemakaian = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        formPemakaian = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jumlahPemakaian = new javax.swing.JSpinner();
        userIdPemakaian = new javax.swing.JTextField();
        prosesPemakaian = new javax.swing.JButton();
        tanggalPemakaian = new com.toedter.calendar.JDateChooser();
        atkOrders2 = new javax.swing.JPanel();
        okButton2 = new javax.swing.JButton();
        viewPemakaian = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPemakaian = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailPemakaian = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bookingButton = new javax.swing.JButton();
        pemakaianButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 769));

        penggunaan.setBackground(new java.awt.Color(255, 255, 255));
        penggunaan.setLayout(new java.awt.CardLayout());

        jTabbedPane1.setToolTipText("");

        jLabel1.setText("NIM/NIP");

        jLabel2.setText("Tanggal Pesan");

        jLabel3.setText("Jumlah Jenis ATK");

        jumlahBooking.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        prosesBooking.setText("Proses");
        prosesBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesBookingActionPerformed(evt);
            }
        });

        tanggalBooking.setDateFormatString("yyyy-MM-dd");

        okButton1.setText("OK");
        okButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBookingLayout = new javax.swing.GroupLayout(formBooking);
        formBooking.setLayout(formBookingLayout);
        formBookingLayout.setHorizontalGroup(
            formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBookingLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formBookingLayout.createSequentialGroup()
                        .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50)
                        .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIdBooking)
                            .addComponent(jumlahBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                    .addGroup(formBookingLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(okButton1)
                            .addComponent(prosesBooking)))
                    .addComponent(atkOrders1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(638, Short.MAX_VALUE))
        );
        formBookingLayout.setVerticalGroup(
            formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBookingLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userIdBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(tanggalBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jumlahBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prosesBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atkOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Form", formBooking);

        tabelBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBooking);

        hapus.setText("Hapus");

        detailBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        detailBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailBookingMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(detailBooking);

        javax.swing.GroupLayout viewBookingLayout = new javax.swing.GroupLayout(viewBooking);
        viewBooking.setLayout(viewBookingLayout);
        viewBookingLayout.setHorizontalGroup(
            viewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBookingLayout.createSequentialGroup()
                .addContainerGap(603, Short.MAX_VALUE)
                .addComponent(hapus)
                .addGap(402, 402, 402))
            .addGroup(viewBookingLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewBookingLayout.setVerticalGroup(
            viewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewBookingLayout.createSequentialGroup()
                .addGroup(viewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewBookingLayout.createSequentialGroup()
                        .addContainerGap(67, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewBookingLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addComponent(hapus)
                .addGap(102, 102, 102))
        );

        jTabbedPane1.addTab("View", viewBooking);

        javax.swing.GroupLayout bookingLayout = new javax.swing.GroupLayout(booking);
        booking.setLayout(bookingLayout);
        bookingLayout.setHorizontalGroup(
            bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        bookingLayout.setVerticalGroup(
            bookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        penggunaan.add(booking, "booking");

        jLabel4.setText("NIM/NIP");

        jLabel5.setText("Tanggal Pesan");

        jLabel6.setText("Jumlah Jenis ATK");

        prosesPemakaian.setText("Proses");
        prosesPemakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesPemakaianActionPerformed(evt);
            }
        });

        tanggalPemakaian.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout atkOrders2Layout = new javax.swing.GroupLayout(atkOrders2);
        atkOrders2.setLayout(atkOrders2Layout);
        atkOrders2Layout.setHorizontalGroup(
            atkOrders2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        atkOrders2Layout.setVerticalGroup(
            atkOrders2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        okButton2.setText("OK");
        okButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPemakaianLayout = new javax.swing.GroupLayout(formPemakaian);
        formPemakaian.setLayout(formPemakaianLayout);
        formPemakaianLayout.setHorizontalGroup(
            formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPemakaianLayout.createSequentialGroup()
                .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okButton2)
                    .addComponent(atkOrders2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formPemakaianLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(42, 42, 42)
                            .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jumlahPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userIdPemakaian)
                                .addComponent(tanggalPemakaian, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                        .addGroup(formPemakaianLayout.createSequentialGroup()
                            .addGap(292, 292, 292)
                            .addComponent(prosesPemakaian))))
                .addContainerGap(698, Short.MAX_VALUE))
        );
        formPemakaianLayout.setVerticalGroup(
            formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPemakaianLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userIdPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tanggalPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jumlahPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prosesPemakaian)
                .addGap(18, 18, 18)
                .addComponent(atkOrders2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton2)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("formPemakaian", formPemakaian);

        tabelPemakaian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPemakaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemakaianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPemakaian);

        jButton3.setText("Hapus");

        detailPemakaian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(detailPemakaian);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Detail Pemakaian");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Daftar Pemakaian");

        javax.swing.GroupLayout viewPemakaianLayout = new javax.swing.GroupLayout(viewPemakaian);
        viewPemakaian.setLayout(viewPemakaianLayout);
        viewPemakaianLayout.setHorizontalGroup(
            viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPemakaianLayout.createSequentialGroup()
                .addGroup(viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPemakaianLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(viewPemakaianLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewPemakaianLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(viewPemakaianLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        viewPemakaianLayout.setVerticalGroup(
            viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPemakaianLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(viewPemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(438, 438, 438))
        );

        jTabbedPane2.addTab("viewPemakaian", viewPemakaian);

        javax.swing.GroupLayout pemakaianLayout = new javax.swing.GroupLayout(pemakaian);
        pemakaian.setLayout(pemakaianLayout);
        pemakaianLayout.setHorizontalGroup(
            pemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemakaianLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pemakaianLayout.setVerticalGroup(
            pemakaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemakaianLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        penggunaan.add(pemakaian, "pemakaian");

        bookingButton.setText("Booking");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        pemakaianButton.setText("Pemakaian");
        pemakaianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemakaianButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bookingButton)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pemakaianButton)
                        .addGap(18, 18, 18)))
                .addComponent(penggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(bookingButton)
                .addGap(18, 18, 18)
                .addComponent(pemakaianButton)
                .addContainerGap(504, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 145, Short.MAX_VALUE)
                .addComponent(penggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed
        pemakaianController.openBooking();
    }//GEN-LAST:event_bookingButtonActionPerformed

    private void prosesBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesBookingActionPerformed
        atkOrders1.removeAll();
        
        int count= (Integer)jumlahBooking.getValue();
        Vector<String> atkName = pemakaianController.getATKName(); 
        createOrders(count, atkName,1);
        
        booking.revalidate();
        booking.repaint();
        okButton1.setVisible(true);
    }//GEN-LAST:event_prosesBookingActionPerformed

    private void prosesPemakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesPemakaianActionPerformed
        atkOrders2.removeAll();
        
        int count= (Integer)jumlahPemakaian.getValue();
        Vector<String> atkName = pemakaianController.getATKName(); 
        createOrders(count, atkName, 2);
        
        booking.revalidate();
        booking.repaint();
        okButton2.setVisible(true);
    }//GEN-LAST:event_prosesPemakaianActionPerformed

    private void okButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton1ActionPerformed
        int count= (Integer)jumlahBooking.getValue();
        Component[] components = atkOrders1.getComponents();
       
        
        String userId= userIdBooking.getText();
        java.util.Date date= (java.util.Date) tanggalBooking.getDate();
      
        for(int i=0; i<count; i++) {
            javax.swing.JPanel panel = (javax.swing.JPanel) components[i];
            javax.swing.JComboBox itemComp = (javax.swing.JComboBox) panel.getComponent(1);
            javax.swing.JSpinner jumlahComp = (javax.swing.JSpinner) panel.getComponent(3);
            
            String ATKname = (String) itemComp.getSelectedItem();
            int sum = (Integer) jumlahComp.getValue(); 
            
            pemakaianController.addBooking(userId,date,ATKname, sum);       
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Booking Berhasil Dimasukkan", "Success!", javax.swing.JOptionPane.PLAIN_MESSAGE);
   
    }//GEN-LAST:event_okButton1ActionPerformed

    private void pemakaianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemakaianButtonActionPerformed
       pemakaianController.openPemakaian();
    }//GEN-LAST:event_pemakaianButtonActionPerformed

    private void okButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton2ActionPerformed
        int count= (Integer)jumlahPemakaian.getValue();
        Component[] components = atkOrders2.getComponents();
       
        int j=0;
        boolean available=true;
        
        while(j<count && available) {
            javax.swing.JPanel panel = (javax.swing.JPanel) components[j];
            javax.swing.JComboBox itemComp = (javax.swing.JComboBox) panel.getComponent(1);
            javax.swing.JSpinner jumlahComp = (javax.swing.JSpinner) panel.getComponent(3);
            
            String ATKname = (String) itemComp.getSelectedItem();
            int sum = (Integer) jumlahComp.getValue(); 
            
            if(pemakaianController.isPemakaianAvailable(ATKname,sum)) {
                j++;
            }
            else {  
                available=false;
            }
        }
      
        if(!available) {
                 javax.swing.JOptionPane.showMessageDialog(this, "Jumlah pemakaian melebih stok tersedia",
                "Pemakaian Ditolak", javax.swing.JOptionPane.WARNING_MESSAGE);  
        }
        else {
            String userId= userIdPemakaian.getText();
            java.util.Date date= (java.util.Date) tanggalPemakaian.getDate();

            for(int i=0; i<count; i++) {
                javax.swing.JPanel panel = (javax.swing.JPanel) components[i];
                javax.swing.JComboBox itemComp = (javax.swing.JComboBox) panel.getComponent(1);
                javax.swing.JSpinner jumlahComp = (javax.swing.JSpinner) panel.getComponent(3);

                String ATKname = (String) itemComp.getSelectedItem();
                int sum = (Integer) jumlahComp.getValue(); 

                pemakaianController.addPemakaian(userId,date,ATKname, sum); 
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Pemakain Berhasil Dimasukkan", "Sucess", javax.swing.JOptionPane.PLAIN_MESSAGE);

        }
    }//GEN-LAST:event_okButton2ActionPerformed

    private void tabelPemakaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemakaianMouseClicked
        nPemakaian= getNameFromTable(tabelPemakaian.getSelectedRow());
        tPemakaian= getDateFromTable(tabelPemakaian.getSelectedRow());
        pemakaianController.viewDetailPemakaian(nPemakaian, tPemakaian);
    }//GEN-LAST:event_tabelPemakaianMouseClicked

    private void detailBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailBookingMouseClicked
        
    }//GEN-LAST:event_detailBookingMouseClicked

    private void tabelBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBookingMouseClicked
        nBooking= getNameFromBookingTable(tabelBooking.getSelectedRow());
        tBooking= getDateFromBookingTable(tabelBooking.getSelectedRow());
        pemakaianController.viewDetailBooking(nBooking, tBooking);
    }//GEN-LAST:event_tabelBookingMouseClicked
    public String getNameFromTable(int row){
        return (String) tabelPemakaian.getValueAt(row,1 );
    }
    public String getDateFromTable(int row){
        return (String) tabelPemakaian.getValueAt(row,2 );
    }
    public String getNameFromBookingTable(int row){
        return (String) tabelBooking.getValueAt(row,1 );
    }
    public String getDateFromBookingTable(int row){
        return (String) tabelBooking.getValueAt(row,2 );
    }
    public void changeScreen(String screenName) {
        ((java.awt.CardLayout)penggunaan.getLayout()).show(penggunaan,screenName);
    }
    
    public void initBookingTable(DefaultTableModel model) {
        tabelBooking.setModel(model);
        tabelBooking.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabelBooking.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelBooking.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelBooking.getColumnModel().getColumn(3).setPreferredWidth(100);
    }
    public void initPemakaianTable(DefaultTableModel model) {
        tabelPemakaian.setModel(model);
        tabelPemakaian.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabelPemakaian.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelPemakaian.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelPemakaian.getColumnModel().getColumn(3).setPreferredWidth(100);
    }
    public void initDetailPemakaianTable(DefaultTableModel model) {
        detailPemakaian.setModel(model);
        detailPemakaian.getColumnModel().getColumn(0).setPreferredWidth(100);
        detailPemakaian.getColumnModel().getColumn(1).setPreferredWidth(100);
        detailPemakaian.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    public void initDetailBookingTable(DefaultTableModel model) {
        detailBooking.setModel(model);
        detailBooking.getColumnModel().getColumn(0).setPreferredWidth(100);
        detailBooking.getColumnModel().getColumn(1).setPreferredWidth(100);
        detailBooking.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    private void createOrders(int count, Vector<String> atkName, int state){
        atkOrders1.setLayout(new GridLayout(10,1));
        atkOrders2.setLayout(new GridLayout(10,1));
        
        for(int i=1; i<=count; i++){
            javax.swing.JPanel panel = new javax.swing.JPanel(new GridLayout(0,4));
            
            
            String itemname = "item" + i;
            String jumlahname = "jumlah" +i;
            javax.swing.JComboBox item = new javax.swing.JComboBox(atkName);
            javax.swing.JSpinner jumlah = new javax.swing.JSpinner();
            javax.swing.JLabel itemLabel = new javax.swing.JLabel("Item: ");
            javax.swing.JLabel jumlahLabel = new javax.swing.JLabel("Jumlah: ");
            
            panel.add(itemLabel, BorderLayout.EAST);
            panel.add(item);
            panel.add(jumlahLabel, BorderLayout.EAST);
            panel.add(jumlah);
            
            item.setName(itemname);
            jumlah.setName(jumlahname);
            itemLabel.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
            jumlahLabel.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
            if(state==1)
                atkOrders1.add(panel);
            else
                atkOrders2.add(panel);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemakaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemakaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atkOrders1;
    private javax.swing.JPanel atkOrders2;
    private javax.swing.JPanel booking;
    private javax.swing.JButton bookingButton;
    private javax.swing.JTable detailBooking;
    private javax.swing.JTable detailPemakaian;
    private javax.swing.JPanel formBooking;
    private javax.swing.JPanel formPemakaian;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JSpinner jumlahBooking;
    private javax.swing.JSpinner jumlahPemakaian;
    private javax.swing.JButton okButton1;
    private javax.swing.JButton okButton2;
    private javax.swing.JPanel pemakaian;
    private javax.swing.JButton pemakaianButton;
    private javax.swing.JPanel penggunaan;
    private javax.swing.JButton prosesBooking;
    private javax.swing.JButton prosesPemakaian;
    private javax.swing.JTable tabelBooking;
    private javax.swing.JTable tabelPemakaian;
    private com.toedter.calendar.JDateChooser tanggalBooking;
    private com.toedter.calendar.JDateChooser tanggalPemakaian;
    private javax.swing.JTextField userIdBooking;
    private javax.swing.JTextField userIdPemakaian;
    private javax.swing.JPanel viewBooking;
    private javax.swing.JPanel viewPemakaian;
    // End of variables declaration//GEN-END:variables
}
