/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventaris.atk.view;

import inventaris.atk.controllers.PengadaanController;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.Box;
import javax.swing.table.DefaultTableModel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;


/**
 *
 * @author FiqieUlya
 */
public class Pengadaan extends javax.swing.JFrame {

    private final PengadaanController pengadaanController;
    private int idTemp = 0;
    /**
     * Creates new form Pengadaan
     */
    public Pengadaan() {
        
        initComponents();
        okButton.setVisible(false);
        pengadaanController = new PengadaanController(this);
        updatePemasokComboBox();
        formDetilATKScrollPane.setVisible(false);
        formDetilATKScrollPane.setViewportView(dummyPanel);
        formDetilATKScrollPane.revalidate();
        formDetilATKScrollPane.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kedatanganMainPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        formDetilATKScrollPane = new javax.swing.JScrollPane();
        dummyPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jumlahJenisAtkLabel = new javax.swing.JLabel();
        namaPemasokLabel = new javax.swing.JLabel();
        namaPemasokComboBox = new javax.swing.JComboBox<String>();
        jumlahJenisAtkSpinner = new javax.swing.JSpinner();
        prosesButton = new javax.swing.JButton();
        kedatanganPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kedatanganTable = new javax.swing.JTable();
        validasiButton = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        viewPanel = new javax.swing.JPanel();
        hapus2Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pengadaanTable = new javax.swing.JTable();
        menuPanel = new javax.swing.JPanel();
        formMenuButton = new javax.swing.JButton();
        kedatanganMenuButton = new javax.swing.JButton();
        viewMenuButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 769));

        kedatanganMainPanel.setLayout(new java.awt.CardLayout());

        formDetilATKScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        formDetilATKScrollPane.setBorder(null);
        formDetilATKScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout dummyPanelLayout = new javax.swing.GroupLayout(dummyPanel);
        dummyPanel.setLayout(dummyPanelLayout);
        dummyPanelLayout.setHorizontalGroup(
            dummyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        dummyPanelLayout.setVerticalGroup(
            dummyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        okButton.setBackground(new java.awt.Color(112, 112, 255));
        okButton.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        okButton.setForeground(new java.awt.Color(255, 255, 255));
        okButton.setText("OK");
        okButton.setBorderPainted(false);
        okButton.setContentAreaFilled(false);
        okButton.setFocusPainted(false);
        okButton.setOpaque(true);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jumlahJenisAtkLabel.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        jumlahJenisAtkLabel.setText("Jumlah Jenis ATK");

        namaPemasokLabel.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        namaPemasokLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaPemasokLabel.setText("Nama Pemasok");

        namaPemasokComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        namaPemasokComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPemasokComboBoxActionPerformed(evt);
            }
        });

        jumlahJenisAtkSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jumlahJenisAtkSpinner.setMinimumSize(new java.awt.Dimension(50, 30));

        prosesButton.setBackground(new java.awt.Color(112, 112, 255));
        prosesButton.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        prosesButton.setForeground(new java.awt.Color(255, 255, 255));
        prosesButton.setText("Proses");
        prosesButton.setBorderPainted(false);
        prosesButton.setContentAreaFilled(false);
        prosesButton.setFocusPainted(false);
        prosesButton.setOpaque(true);
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaPemasokLabel)
                    .addComponent(jumlahJenisAtkLabel))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaPemasokComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jumlahJenisAtkSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addComponent(prosesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPemasokComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPemasokLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahJenisAtkSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jumlahJenisAtkLabel))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(prosesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(formDetilATKScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dummyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(473, 473, 473))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(dummyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(formDetilATKScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        kedatanganMainPanel.add(formPanel, "formPanel");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        kedatanganTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(kedatanganTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        validasiButton.setBackground(new java.awt.Color(112, 112, 255));
        validasiButton.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        validasiButton.setForeground(new java.awt.Color(255, 255, 255));
        validasiButton.setBorderPainted(false);
        validasiButton.setContentAreaFilled(false);
        validasiButton.setFocusPainted(false);
        validasiButton.setLabel("Validasi Kedatangan");
        validasiButton.setOpaque(true);
        validasiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validasiButtonActionPerformed(evt);
            }
        });

        buttonHapus.setBackground(new java.awt.Color(112, 112, 255));
        buttonHapus.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setBorderPainted(false);
        buttonHapus.setContentAreaFilled(false);
        buttonHapus.setFocusPainted(false);
        buttonHapus.setLabel("Hapus");
        buttonHapus.setOpaque(true);
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kedatanganPanelLayout = new javax.swing.GroupLayout(kedatanganPanel);
        kedatanganPanel.setLayout(kedatanganPanelLayout);
        kedatanganPanelLayout.setHorizontalGroup(
            kedatanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kedatanganPanelLayout.createSequentialGroup()
                .addGroup(kedatanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kedatanganPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kedatanganPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(validasiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(546, Short.MAX_VALUE))
        );
        kedatanganPanelLayout.setVerticalGroup(
            kedatanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kedatanganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kedatanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validasiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        kedatanganMainPanel.add(kedatanganPanel, "kedatanganPanel");

        hapus2Button.setBackground(new java.awt.Color(112, 112, 255));
        hapus2Button.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        hapus2Button.setForeground(new java.awt.Color(255, 255, 255));
        hapus2Button.setText("Hapus");
        hapus2Button.setBorderPainted(false);
        hapus2Button.setContentAreaFilled(false);
        hapus2Button.setFocusPainted(false);
        hapus2Button.setOpaque(true);
        hapus2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus2ButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        pengadaanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(pengadaanTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hapus2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(719, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hapus2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        kedatanganMainPanel.add(viewPanel, "viewPanel");

        menuPanel.setBackground(new java.awt.Color(153, 153, 153));
        menuPanel.setPreferredSize(new java.awt.Dimension(200, 769));

        formMenuButton.setBackground(new java.awt.Color(51, 51, 51));
        formMenuButton.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        formMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        formMenuButton.setBorderPainted(false);
        formMenuButton.setContentAreaFilled(false);
        formMenuButton.setFocusPainted(false);
        formMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formMenuButton.setLabel("Form");
        formMenuButton.setOpaque(true);
        formMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formMenuButtonActionPerformed(evt);
            }
        });

        kedatanganMenuButton.setBackground(new java.awt.Color(153, 153, 153));
        kedatanganMenuButton.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        kedatanganMenuButton.setForeground(new java.awt.Color(204, 204, 204));
        kedatanganMenuButton.setBorderPainted(false);
        kedatanganMenuButton.setContentAreaFilled(false);
        kedatanganMenuButton.setFocusPainted(false);
        kedatanganMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kedatanganMenuButton.setLabel("Kedatangan");
        kedatanganMenuButton.setOpaque(true);
        kedatanganMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kedatanganMenuButtonActionPerformed(evt);
            }
        });

        viewMenuButton.setBackground(new java.awt.Color(153, 153, 153));
        viewMenuButton.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        viewMenuButton.setForeground(new java.awt.Color(204, 204, 204));
        viewMenuButton.setBorderPainted(false);
        viewMenuButton.setContentAreaFilled(false);
        viewMenuButton.setFocusPainted(false);
        viewMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewMenuButton.setLabel("View");
        viewMenuButton.setOpaque(true);
        viewMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMenuButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 102));
        jButton1.setFont(new java.awt.Font("DokChampa", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logo");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kedatanganMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(viewMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kedatanganMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kedatanganMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kedatanganMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void formMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formMenuButtonActionPerformed
        int n = (int) jumlahJenisAtkSpinner.getValue();
        pengadaanController.openForm(n);
        this.formMenuButton.setBackground(Color.darkGray);
        this.formMenuButton.setForeground(Color.white);
        this.kedatanganMenuButton.setBackground(new Color(153,153,153));
        this.kedatanganMenuButton.setForeground(new Color(204,204,204));
        this.viewMenuButton.setBackground(new Color(153,153,153));
        this.viewMenuButton.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_formMenuButtonActionPerformed

    private void kedatanganMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kedatanganMenuButtonActionPerformed
        pengadaanController.openKedatangan();
        this.formMenuButton.setBackground(new Color(153,153,153));
        this.formMenuButton.setForeground(new Color(204,204,204));
        this.kedatanganMenuButton.setBackground(Color.darkGray);
        this.kedatanganMenuButton.setForeground(Color.white);
        this.viewMenuButton.setBackground(new Color(153,153,153));
        this.viewMenuButton.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_kedatanganMenuButtonActionPerformed

    private void viewMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMenuButtonActionPerformed
        pengadaanController.openView();
        this.formMenuButton.setBackground(new Color(153,153,153));
        this.formMenuButton.setForeground(new Color(204,204,204));
        this.kedatanganMenuButton.setBackground(new Color(153,153,153));
        this.kedatanganMenuButton.setForeground(new Color(204,204,204));
        this.viewMenuButton.setBackground(Color.darkGray);
        this.viewMenuButton.setForeground(Color.white);
    }//GEN-LAST:event_viewMenuButtonActionPerformed

    private void validasiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validasiButtonActionPerformed

        
        pengadaanController.validasi(kedatanganTable.getSelectedRow());
        
        
        /*String kategori= (String) category.getSelectedItem();
        String id = idUser.getText();
        inventarisController.updateUser(nama, id, kategori);
        private void userTableMouseClicked(java.awt.event.MouseEvent evt) {                                       
        userName.setText((String)getUserNameFromTable(userTable.getSelectedRow()));
        category.setSelectedItem(getUserCategoryFromTable(userTable.getSelectedRow() ));
        idUser.setText((String)getUserIdFromTable(userTable.getSelectedRow()));*/
    
    }//GEN-LAST:event_validasiButtonActionPerformed

    private void namaPemasokComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPemasokComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPemasokComboBoxActionPerformed
 
    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        int n = (int) jumlahJenisAtkSpinner.getValue();
        pengadaanController.prosesForm(n);
        if(n > 0){
            
            dummyPanel.removeAll();
            Vector<String> atkIdName = pengadaanController.getATKIdName();
            createOrders(n, atkIdName);
            formDetilATKScrollPane.setViewportView(dummyPanel);
            formDetilATKScrollPane.revalidate();
            formDetilATKScrollPane.repaint();
            formPanel.revalidate();
            formPanel.repaint();
            okButton.setVisible(true);
            formDetilATKScrollPane.setVisible(true);
        }else{
            okButton.setVisible(false);
            formDetilATKScrollPane.setVisible(false);
        }
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        int n = (int) jumlahJenisAtkSpinner.getValue();
        Component[] components = dummyPanel.getComponents();
      
        
        String id_pemasok = (String) namaPemasokComboBox.getSelectedItem();
        String[] array_pemasok = id_pemasok.split("\\ - ", -1);
        id_pemasok = array_pemasok[0];
        
        boolean adaMasuk = false;
        for(int i=0; i<n; i++) {
            javax.swing.JPanel panel = (javax.swing.JPanel) components[i];
            javax.swing.JComboBox itemComp = (javax.swing.JComboBox) panel.getComponent(1);
            javax.swing.JSpinner jumlahComp = (javax.swing.JSpinner) panel.getComponent(3);
            
            int stok = (Integer) jumlahComp.getValue(); 
            if(stok > 0){
                adaMasuk = true;
                String tanggal_pesan = "DateTime('now', '+"+i+" seconds')";
                String id_ATK = (String) itemComp.getSelectedItem();
                String[] array_item = id_ATK.split("\\ - ", -1);
                id_ATK = array_item[0];

                pengadaanController.createPengadaan(stok, tanggal_pesan, Integer.parseInt(id_pemasok), Integer.parseInt(id_ATK));    
            }
        }
        if(adaMasuk){
            javax.swing.JOptionPane.showMessageDialog(this, "Pengadaan Berhasil Dimasukkan", "Success!", javax.swing.JOptionPane.PLAIN_MESSAGE);
            okButton.setVisible(false);
            formDetilATKScrollPane.setVisible(false);
            jumlahJenisAtkSpinner.setValue(0);
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada pengadaan yang dapat dimasukkan", "Ulangi", javax.swing.JOptionPane.PLAIN_MESSAGE);
        }

//reset
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        if(kedatanganTable.getSelectedRow() != -1){
            pengadaanController.hapusKedatangan(kedatanganTable.getSelectedRow());
            
            
            //initKinitedatanganTable(kedatanganTableModel);
            /*SwingUtilities.updateComponentTreeUI(this);
            invalidate();
            validate();
            repaint();*/
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void hapus2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus2ButtonActionPerformed
        if(pengadaanTable.getSelectedRow() != -1){
            String tanggal_pesan= (String) pengadaanTable.getValueAt(pengadaanTable.getSelectedRow(),3);
            Integer id_pemasok= (Integer) pengadaanTable.getValueAt(pengadaanTable.getSelectedRow(),5);
            Integer id_atk= (Integer) pengadaanTable.getValueAt(pengadaanTable.getSelectedRow(),6);

            pengadaanController.deletePengadaan(id_atk, tanggal_pesan, id_pemasok);
            javax.swing.JOptionPane.showMessageDialog(this, "Hapus berhasil", "Success!", javax.swing.JOptionPane.PLAIN_MESSAGE);
            pengadaanController.openView();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_hapus2ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu main = new MainMenu();
        pengadaanController.changeFrame(main);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void createOrders(int count, Vector<String> supplierName){
        dummyPanel.setLayout(new GridLayout(10,1));
        
        for(int i=1; i<=count; i++){
            javax.swing.JPanel panel = new javax.swing.JPanel(new GridLayout(0,4));
            panel.setSize(500, 300);
            String itemname = "item" + i;
            String jumlahname = "jumlah" +i;
            javax.swing.JComboBox item = new javax.swing.JComboBox(supplierName);
            javax.swing.JSpinner jumlah = new javax.swing.JSpinner();
            jumlah.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
            jumlah.setPreferredSize(new java.awt.Dimension(5, 5));
            javax.swing.JLabel itemLabel = new javax.swing.JLabel("Item: ");
            //itemLabel.setSize(10, 30);
            javax.swing.JLabel jumlahLabel = new javax.swing.JLabel("Jumlah: ");
            //jumlahLabel.setSize(10, 30);
            panel.add(itemLabel);
            panel.add(item);
            //panel.add(Box.createRigidArea(new Dimension(5,0)));
            panel.add(jumlahLabel);
            panel.add(jumlah);
            
            item.setName(itemname);
            jumlah.setName(jumlahname);
            //itemLabel.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
            //jumlahLabel.setHorizontalTextPosition(javax.swing.JLabel.RIGHT);
            dummyPanel.setSize(500, 300);
            dummyPanel.add(panel);
        }
    }
    
    public void updatePemasokComboBox(){
        Vector<String> namaPemasok = pengadaanController.getSupplierIdName();
        namaPemasokComboBox.removeAllItems();
        for(String nama: namaPemasok)
            namaPemasokComboBox.addItem(nama);
    }
    
    public void changeScreen(String panel){
        CardLayout card = (CardLayout)kedatanganMainPanel.getLayout();
        card.show(kedatanganMainPanel, panel);
    }
    
    public void initKedatanganTable(DefaultTableModel model) {
        kedatanganTable.setModel(model);
        kedatanganTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        kedatanganTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        kedatanganTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        kedatanganTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        kedatanganTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        //kedatanganTable.getColumnModel().removeColumn(kedatanganTable.getCol);
    }
    
    public void initPengadaanTable(DefaultTableModel model) {
        pengadaanTable.setModel(model);
        pengadaanTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        pengadaanTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        pengadaanTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        pengadaanTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        pengadaanTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        pengadaanTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        pengadaanTable.getColumnModel().getColumn(6).setPreferredWidth(100);
    }
    
    public void showDialogBox(String message, String message2){
        javax.swing.JOptionPane.showMessageDialog(this, message, message2, javax.swing.JOptionPane.PLAIN_MESSAGE);
    }
            
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengadaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JPanel dummyPanel;
    private javax.swing.JScrollPane formDetilATKScrollPane;
    private javax.swing.JButton formMenuButton;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton hapus2Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jumlahJenisAtkLabel;
    private javax.swing.JSpinner jumlahJenisAtkSpinner;
    private javax.swing.JPanel kedatanganMainPanel;
    private javax.swing.JButton kedatanganMenuButton;
    private javax.swing.JPanel kedatanganPanel;
    private javax.swing.JTable kedatanganTable;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JComboBox<String> namaPemasokComboBox;
    private javax.swing.JLabel namaPemasokLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JTable pengadaanTable;
    private javax.swing.JButton prosesButton;
    private javax.swing.JButton validasiButton;
    private javax.swing.JButton viewMenuButton;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables

}
