package inventaris.atk.view;
import inventaris.atk.controllers.StatistikController;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

public class Statistik extends javax.swing.JFrame {
    
    private final StatistikController statistikController;

    public Statistik() {
        initComponents();
        statistikController = new StatistikController(this);
        int selectedYear = (int) year.getYear();
        int selectedMonth = (int) month.getMonth();
        statistikController.openPeriode(selectedMonth, selectedYear);
        
    }
    
    public void changeScreen(String screenName) {
        ((java.awt.CardLayout)statistik.getLayout()).show(statistik,screenName);
    }
    
    public void initPeriodeTable(DefaultTableModel model) {
        periodeTable.setModel(model);
        periodeTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        periodeTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        periodeTable.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    
    public void initUserTable(DefaultTableModel model) {
        userTable.setModel(model);
        userTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        userTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        userTable.getColumnModel().getColumn(2).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        statistik = new javax.swing.JPanel();
        Periode = new javax.swing.JPanel();
        form_periode = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        year = new com.toedter.calendar.JYearChooser();
        month = new com.toedter.calendar.JMonthChooser();
        periodeShowButton = new javax.swing.JButton();
        result_periode = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        periodeTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        User = new javax.swing.JPanel();
        result_user = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        form_user = new javax.swing.JPanel();
        userShowButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        year_user = new com.toedter.calendar.JYearChooser();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        subMenu = new javax.swing.JPanel();
        statPeriodeMenuButton = new javax.swing.JButton();
        statPenggunaMenuButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 769));

        statistik.setBackground(new java.awt.Color(204, 204, 204));
        statistik.setPreferredSize(new java.awt.Dimension(1166, 769));
        statistik.setLayout(new java.awt.CardLayout());

        form_periode.setBackground(new java.awt.Color(255, 255, 255));
        form_periode.setPreferredSize(new java.awt.Dimension(270, 190));

        jLabel1.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        jLabel1.setText("Tahun");

        jLabel2.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        jLabel2.setText("Bulan");

        month.setDoubleBuffered(false);

        periodeShowButton.setBackground(new java.awt.Color(112, 112, 255));
        periodeShowButton.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        periodeShowButton.setForeground(new java.awt.Color(255, 255, 255));
        periodeShowButton.setText("Tampilkan");
        periodeShowButton.setBorderPainted(false);
        periodeShowButton.setContentAreaFilled(false);
        periodeShowButton.setFocusPainted(false);
        periodeShowButton.setOpaque(true);
        periodeShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodeShowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout form_periodeLayout = new javax.swing.GroupLayout(form_periode);
        form_periode.setLayout(form_periodeLayout);
        form_periodeLayout.setHorizontalGroup(
            form_periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_periodeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(periodeShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        form_periodeLayout.setVerticalGroup(
            form_periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_periodeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(form_periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(periodeShowButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        result_periode.setBackground(new java.awt.Color(255, 255, 255));

        periodeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Bulan", "ATK", "Pemakaian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(periodeTable);

        javax.swing.GroupLayout result_periodeLayout = new javax.swing.GroupLayout(result_periode);
        result_periode.setLayout(result_periodeLayout);
        result_periodeLayout.setHorizontalGroup(
            result_periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result_periodeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        result_periodeLayout.setVerticalGroup(
            result_periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result_periodeLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Jumlah Pemakaian");

        javax.swing.GroupLayout PeriodeLayout = new javax.swing.GroupLayout(Periode);
        Periode.setLayout(PeriodeLayout);
        PeriodeLayout.setHorizontalGroup(
            PeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeriodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(form_periode, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                        .addComponent(result_periode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addContainerGap(571, Short.MAX_VALUE))
        );
        PeriodeLayout.setVerticalGroup(
            PeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeriodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form_periode, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result_periode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(492, Short.MAX_VALUE))
        );

        statistik.add(Periode, "Periode");

        User.setPreferredSize(new java.awt.Dimension(1166, 769));

        result_user.setBackground(new java.awt.Color(255, 255, 255));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Bulan", "ATK", "Pemakaian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(userTable);

        javax.swing.GroupLayout result_userLayout = new javax.swing.GroupLayout(result_user);
        result_user.setLayout(result_userLayout);
        result_userLayout.setHorizontalGroup(
            result_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result_userLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        result_userLayout.setVerticalGroup(
            result_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result_userLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        form_user.setBackground(new java.awt.Color(255, 255, 255));

        userShowButton.setBackground(new java.awt.Color(102, 102, 255));
        userShowButton.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        userShowButton.setForeground(new java.awt.Color(255, 255, 255));
        userShowButton.setText("Tampilkan");
        userShowButton.setContentAreaFilled(false);
        userShowButton.setFocusPainted(false);
        userShowButton.setOpaque(true);
        userShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userShowButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        jLabel3.setText("Tahun");

        jLabel4.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        jLabel4.setText("Pengguna");

        username.setEditable(true);
        username.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tata Usaha", "Dosen", "Lain-lain" }));
        username.setFocusable(false);

        javax.swing.GroupLayout form_userLayout = new javax.swing.GroupLayout(form_user);
        form_user.setLayout(form_userLayout);
        form_userLayout.setHorizontalGroup(
            form_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_userLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(year_user, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        form_userLayout.setVerticalGroup(
            form_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_userLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(form_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username)
                    .addComponent(year_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(form_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Jumlah Pemakaian");

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User);
        User.setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(572, Short.MAX_VALUE))
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        statistik.add(User, "User");

        subMenu.setBackground(new java.awt.Color(153, 153, 153));
        subMenu.setPreferredSize(new java.awt.Dimension(200, 769));

        statPeriodeMenuButton.setBackground(new java.awt.Color(51, 51, 51));
        statPeriodeMenuButton.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        statPeriodeMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        statPeriodeMenuButton.setText("Pemakaian ATK per Periode");
        statPeriodeMenuButton.setBorderPainted(false);
        statPeriodeMenuButton.setContentAreaFilled(false);
        statPeriodeMenuButton.setFocusPainted(false);
        statPeriodeMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statPeriodeMenuButton.setOpaque(true);
        statPeriodeMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statPeriodeMenuButtonActionPerformed(evt);
            }
        });

        statPenggunaMenuButton.setBackground(new java.awt.Color(153, 153, 153));
        statPenggunaMenuButton.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        statPenggunaMenuButton.setForeground(new java.awt.Color(204, 204, 204));
        statPenggunaMenuButton.setText("Pemakaian ATK per User");
        statPenggunaMenuButton.setBorderPainted(false);
        statPenggunaMenuButton.setContentAreaFilled(false);
        statPenggunaMenuButton.setFocusPainted(false);
        statPenggunaMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statPenggunaMenuButton.setOpaque(true);
        statPenggunaMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statPenggunaMenuButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(250, 108, 125));
        jButton3.setFont(new java.awt.Font("DokChampa", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setOpaque(true);
        jButton3.setPreferredSize(new java.awt.Dimension(200, 39));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subMenuLayout = new javax.swing.GroupLayout(subMenu);
        subMenu.setLayout(subMenuLayout);
        subMenuLayout.setHorizontalGroup(
            subMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuLayout.createSequentialGroup()
                .addGroup(subMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statPenggunaMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, subMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(statPeriodeMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        subMenuLayout.setVerticalGroup(
            subMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuLayout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statPeriodeMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statPenggunaMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(537, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(subMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statistik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statistik, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statPenggunaMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statPenggunaMenuButtonActionPerformed
        // TODO add your handling code here:
        int selectedYear = (int) year_user.getYear();
        String selectedKategori = (String) username.getSelectedItem();
        statistikController.openUser(selectedKategori, selectedYear);
        this.statPenggunaMenuButton.setBackground(Color.darkGray);
        this.statPenggunaMenuButton.setForeground(Color.white);
        this.statPeriodeMenuButton.setBackground(new Color(153,153,153));
        this.statPeriodeMenuButton.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_statPenggunaMenuButtonActionPerformed

    private void statPeriodeMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statPeriodeMenuButtonActionPerformed
        // TODO add your handling code here:
        int selectedYear = (int) year.getYear();
        int selectedMonth = (int) month.getMonth();
        statistikController.openPeriode(selectedMonth, selectedYear);
        this.statPeriodeMenuButton.setBackground(Color.darkGray);
        this.statPeriodeMenuButton.setForeground(Color.white);
        this.statPenggunaMenuButton.setBackground(new Color(153,153,153));
        this.statPenggunaMenuButton.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_statPeriodeMenuButtonActionPerformed

    private void userShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userShowButtonActionPerformed
        // TODO add your handling code here:
        int selectedYear = (int) year_user.getYear();
        String selectedKategori = (String) username.getSelectedItem();
        statistikController.showAtSpesificUser(selectedKategori, selectedYear);
    }//GEN-LAST:event_userShowButtonActionPerformed

    private void periodeShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodeShowButtonActionPerformed
        // TODO add your handling code here:
        int selectedYear = (int) year.getYear();
        int selectedMonth = (int) month.getMonth();
        statistikController.showAtSpesificTime(selectedMonth, selectedYear);
    }//GEN-LAST:event_periodeShowButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MainMenu main = new MainMenu();
        statistikController.changeFrame(main);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Periode;
    private javax.swing.JPanel User;
    private javax.swing.JPanel form_periode;
    private javax.swing.JPanel form_user;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JMonthChooser month;
    private javax.swing.JButton periodeShowButton;
    private javax.swing.JTable periodeTable;
    private javax.swing.JPanel result_periode;
    private javax.swing.JPanel result_user;
    private javax.swing.JButton statPenggunaMenuButton;
    private javax.swing.JButton statPeriodeMenuButton;
    private javax.swing.JPanel statistik;
    private javax.swing.JPanel subMenu;
    private javax.swing.JButton userShowButton;
    private javax.swing.JTable userTable;
    private javax.swing.JComboBox username;
    private com.toedter.calendar.JYearChooser year;
    private com.toedter.calendar.JYearChooser year_user;
    // End of variables declaration//GEN-END:variables
}
